### ISSUE TITLE
repp segmentation fault

### ISSUE THREAD

**Issue by arademaker** [delph-in/homebrew-delphin#1]
With the same example used for testing in the formula file:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/86403/86398564-3175ed00-bc7c-11ea-8975-15b91b3b7c90.png">

```
ar@leme ~ % repp teste.rpp
don't
zsh: segmentation fault  repp teste.rpp
ar@leme ~ % repp teste.rpp
do n't
zsh: segmentation fault  repp teste.rpp
```

**Comment by dantiston** [comment]
Hi @arademaker - the test file that is generated looks like this after printing from Ruby:
```
: +
!^(.+)$								 \1 
!([^ ])(n't) 						\1 \2 
```

I was able to confirm that with the escaped backslashes, I get the segmentation fault and without, I do not. I suspect this is a bug in `repp` that we should file with Woodley.

If you run `brew test delph-in/delphin/repp --keep-tmp`, you can inspect the test file (for instance, `/private/tmp/repp-test-20200702-51782-1nbgzhq`), where I can see:
```
$ cat /private/tmp/repp-test-20200702-51782-1nbgzhq/test.rpp 
: +
!^(.+)$								 \1 
!([^ ])(n't) 						\1 \2 
```

**Comment by arademaker** [comment]
Thank you, unfortunately we don’t have repp code in a GitHub repository to easily report an issue. I will write to the dev list
