### ISSUE TITLE
Allow building of HEAD

### ISSUE THREAD

**Issue by arademaker** [delph-in/homebrew-delphin#2]
ACE trunk was updated, how this formula is updated? Is it an automatic or manual process?

```
% svn update
Updating '.':
U    hash.c
U    maxent.c
U    maxent.h
U    unpack.c
U    main.c
U    parse.c
U    unpack.h
Updated to revision 1043.
```

**Comment by arademaker** [comment]
Sorry, I just saw that you are not getting ACE from the SVN, but from the `tar.gz` distribution.

**Comment by arademaker** [comment]
It would be nice, anyway, to have a trunk version somehow... an unstable release...

**Comment by dantiston** [comment]
@arademaker there haven’t been any official releases (that I’ve seen) since this repo was released, so I haven’t crossed that rubicon yet. It isn’t automatic, though.

It is possible to add an option to check out HEAD, so we could keep that open as an issue :-)
